imagepullsecrets: sunbird-registry-secret

### Job manager related vars
jobmanager_rpc_port: 6123
jobmanager_blob_port: 6124
jobmanager_query_port: 6125
jobmanager_ui_port: 8081
jobmanager_prom_port: 9250
jobmanager_heap_memory: 1024
jobmanager_ui_rest_port: 80
jobmanager_ui_tcp_port: 8081
jobmanager_ui_service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

### taskmanager related vars
healthcheck: true
taskmanager_liveness:
  livenessProbe:
    tcpSocket:
      port: 6122
    initialDelaySeconds: 30
    periodSeconds: 60

taskmanager_prom_port: 9251
taskmanager_rpc_port: 6122
taskmanager_heap_memory: 1024

### base-config related vars
postgres_max_connections: 2
flink_container_name: flink-check-points-store
checkpoint_interval: 60000
checkpoint_pause_between_seconds: 5000
checkpoint_compression_enabled: true
restart_attempts: 3
restart_delay: 30000 # in milli-seconds
producer_max_request_size: 1572864

### class name vars
flink_job_names:
  cokreat-user-delete:
    job_class_name: 'org.sunbird.job.task.UserDeleteStreamTask'
    replica: 1
    jobmanager_memory: 2048m
    taskmanager_memory: 2048m
    taskslots: 1
    cpu_requests: 0.3
  metrics-data-transformer:
    job_class_name: 'org.sunbird.job.metricstransformer.task.MetricsDataTransformerStreamTask'
    replica: 1
    jobmanager_memory: 2048m
    taskmanager_memory: 2048m
    taskslots: 1
    cpu_requests: 0.3

### Global vars
cloud_store: azure
service_monitor_enabled: true
job_classname: ""

### controlling the flink jobs log level
flink_jobs_console_log_level: INFO
flink_libraries_log_level: ERROR

### user delete job configuration
user_delete_kafka_topic_name: "{{ sunbird_instance }}.delete.user"
ownership_transfer_kafka_topic_name: "{{ sunbird_instance }}.user.ownership.transfer"
user_delete_group: "{{ sunbird_instance }}_cokreat_user_delete_group"

program_service_baseurl: "http://{{ private_ingressgateway_ip }}/program"

### metrics data transformer job configuration
metrics_data_transformer_kafka_topic_name: "{{ sunbird_instance }}.learning.graph.events"
metrics_data_transformer_group: "{{ sunbird_instance }}-metrics-data-transformer-group"

metrics_data_transformer_consumer_parallelism: 1
metrics_data_transformer_parallelism: 1
metrics_data_transformer_producer_parallelism: 1

ed_content_service_base_url: "http://{{ private_ingressgateway_ip }}/content"
dock_content_service_base_url: "http://{{ dock_private_ingressgateway_ip }}/content"

